import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const INPUT_PATH = path.join(__dirname, "../../words_alpha.txt");
const OUTPUT_PATH = path.join(__dirname, "../lib/wordlist.ts");

const MIN_LENGTH = 3;
const MAX_LENGTH = 6;
const MAX_WORDS = 10000;

const rawWords = fs.readFileSync(INPUT_PATH, "utf-8").split("\n");

const filtered = rawWords
  .map((w) => w.trim().toLowerCase())
  .filter(
    (w) =>
      /^[a-z]+$/.test(w) &&
      w.length >= MIN_LENGTH &&
      w.length <= MAX_LENGTH
  );

const unique = Array.from(new Set(filtered)).slice(0, MAX_WORDS);

const tsExport = `// Auto-generated by generateWordlist.js
export const WORDS = ${JSON.stringify(unique, null, 2)};
`;

fs.writeFileSync(OUTPUT_PATH, tsExport, "utf-8");
console.log(`✅ Generated ${unique.length} words to ${OUTPUT_PATH}`);
